/* Kataxwriseis dimwn */
INSERT INTO Dimoi (Name, Population) VALUES('Αθηναίων', 664046);
INSERT INTO Dimoi (Name, Population) VALUES('Βύρωνος', 61308);
INSERT INTO Dimoi (Name, Population) VALUES('Γαλατσίου', 59345);
INSERT INTO Dimoi (Name, Population) VALUES('Δάφνης – Υμηττού', 33628);
INSERT INTO Dimoi (Name, Population) VALUES('Ζωγράφου', 71026);
INSERT INTO Dimoi (Name, Population) VALUES('Ηλιουπόλεως', 78153);
INSERT INTO Dimoi (Name, Population) VALUES('Καισαριανής', 26458);
INSERT INTO Dimoi (Name, Population) VALUES('Φιλαδελφείας – Χαλκηδόνος', 35556);
INSERT INTO Dimoi (Name, Population) VALUES('Αγίας Παρασκευής', 59704);
INSERT INTO Dimoi (Name, Population) VALUES('Αμαρουσίου', 72333);
INSERT INTO Dimoi (Name, Population) VALUES('Βριλησσίων', 30741);
INSERT INTO Dimoi (Name, Population) VALUES('Ηρακλείου', 49642);
INSERT INTO Dimoi (Name, Population) VALUES('Κηφισιάς', 70600 );
INSERT INTO Dimoi (Name, Population) VALUES('Λυκόβρυσης – Πεύκης', 31002 );
INSERT INTO Dimoi (Name, Population) VALUES('Μεταμορφώσεως', 29891 );
INSERT INTO Dimoi (Name, Population) VALUES('Νέας Ιωνίας', 67134 );
INSERT INTO Dimoi (Name, Population) VALUES('Παπάγου – Χολαργού', 44539 );
INSERT INTO Dimoi (Name, Population) VALUES('Πεντέλης', 34934 );
INSERT INTO Dimoi (Name, Population) VALUES('Φιλοθέης – Ψυχικού', 26968 );
INSERT INTO Dimoi (Name, Population) VALUES('Χαλανδρίου', 74192 );
INSERT INTO Dimoi (Name, Population) VALUES('Περιστερίου', 139981);
INSERT INTO Dimoi (Name, Population) VALUES('Αγίας Βαρβάρας', 26550 );
INSERT INTO Dimoi (Name, Population) VALUES('Αγίων Αναργύρων – Καματερού', 62529 );
INSERT INTO Dimoi (Name, Population) VALUES('Αιγάλεω', 69946 );
INSERT INTO Dimoi (Name, Population) VALUES('Ιλίου', 84793 );
INSERT INTO Dimoi (Name, Population) VALUES('Πετρουπόλεως', 58979 );
INSERT INTO Dimoi (Name, Population) VALUES('Χαϊδαρίου', 46897 );
INSERT INTO Dimoi (Name, Population) VALUES('Καλλιθέας', 100641 );
INSERT INTO Dimoi (Name, Population) VALUES('Αγίου Δημητρίου', 71294 );
INSERT INTO Dimoi (Name, Population) VALUES('Αλίμου', 41720 );
INSERT INTO Dimoi (Name, Population) VALUES('Γλυφάδας', 87305 );
INSERT INTO Dimoi (Name, Population) VALUES('Ελληνικού – Αργυρούπολης', 51356 );
INSERT INTO Dimoi (Name, Population) VALUES('Μοσχάτου – Ταύρου', 40413 );
INSERT INTO Dimoi (Name, Population) VALUES('Νέας Σμύρνης', 73076 );
INSERT INTO Dimoi (Name, Population) VALUES('Παλαιού Φαλήρου', 64021 );
INSERT INTO Dimoi (Name, Population) VALUES('Αχαρνών', 106943);
INSERT INTO Dimoi (Name, Population) VALUES('Βάρης – Βούλας – Βουλιαγμένης', 48399 );
INSERT INTO Dimoi (Name, Population) VALUES('Διονύσου', 40193 );
INSERT INTO Dimoi (Name, Population) VALUES('Κρωπίας', 30307 );
INSERT INTO Dimoi (Name, Population) VALUES('Λαυρεωτικής', 25102 );
INSERT INTO Dimoi (Name, Population) VALUES('Μαραθώνα', 33423 );
INSERT INTO Dimoi (Name, Population) VALUES('Μαρκοπούλου Μεσογαίας', 20040 );
INSERT INTO Dimoi (Name, Population) VALUES('Παιανίας', 26668 );
INSERT INTO Dimoi (Name, Population) VALUES('Παλλήνης', 54415 );
INSERT INTO Dimoi (Name, Population) VALUES('Ραφήνας – Πικερμίου', 20266);
INSERT INTO Dimoi (Name, Population) VALUES('Σαρωνικού', 29002 );
INSERT INTO Dimoi (Name, Population) VALUES('Σπάτων – Αρτέμιδος', 33821 );
INSERT INTO Dimoi (Name, Population) VALUES('Ωρωπού', 33769);
INSERT INTO Dimoi (Name, Population) VALUES('Ελευσίνας', 29902 );
INSERT INTO Dimoi (Name, Population) VALUES('Ασπροπύργου', 30251 );
INSERT INTO Dimoi (Name, Population) VALUES('Μάνδρας – Ειδυλλίας', 17885 );
INSERT INTO Dimoi (Name, Population) VALUES('Μεγαρέων', 36924 );
INSERT INTO Dimoi (Name, Population) VALUES('Φυλής', 45965 );
INSERT INTO Dimoi (Name, Population) VALUES('Πειραιώς', 163688 );
INSERT INTO Dimoi (Name, Population) VALUES('Κερατσινίου – Δραπετσώνας', 91045);
INSERT INTO Dimoi (Name, Population) VALUES('Κορυδαλλού', 63445 );
INSERT INTO Dimoi (Name, Population) VALUES('Νίκαιας – Αγίου Ιωάννη Ρέντη', 105430 );
INSERT INTO Dimoi (Name, Population) VALUES('Περάματος', 25389);
INSERT INTO Dimoi (Name, Population) VALUES('Σαλαμίνος', 39283 );
INSERT INTO Dimoi (Name, Population) VALUES('Αγκιστρίου', 1142 );
INSERT INTO Dimoi (Name, Population) VALUES('Αίγινας', 13056 );
INSERT INTO Dimoi (Name, Population) VALUES('Κυθήρων', 4041 );
INSERT INTO Dimoi (Name, Population) VALUES('Πόρου', 3993 );
INSERT INTO Dimoi (Name, Population) VALUES('Σπετσών', 4027 );
INSERT INTO Dimoi (Name, Population) VALUES('Τροιζηνίας', 7143 );
INSERT INTO Dimoi (Name, Population) VALUES('Ύδρας', 1966 );

INSERT INTO Person1 (name, username) VALUES("paraskos","azako");
INSERT INTO Person1 (name, username) VALUES("antreas","sirkats");
